# Generated by Django 4.1.7 on 2023-06-02 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('total_tracks', models.IntegerField()),
                ('release_date', models.DateField()),
                ('type', models.CharField(max_length=32)),
                ('genres',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True,
                                                           size=None)),
                ('uri', models.CharField(max_length=64)),
                ('external_urls', models.JSONField()),
            ],
        ),
    ]
