# Generated by Django 4.1.7 on 2023-06-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('track', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
        ),
    ]
