version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    volumes:
      - .:/app
    
volumes:
  postgres:
