version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${MAIN_DB}
      POSTGRES_USER: ${MAIN_USER}
      POSTGRES_PASSWORD: ${MAIN_PASSWORD}
      POSTGRES_HOST: ${MAIN_HOST}
      POSTGRES_PORT: ${MAIN_PORT}
