# Generated by Django 4.1.7 on 2023-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('uri', models.CharField(max_length=64)),
                ('external_urls', models.JSONField()),
            ],
        ),
    ]
